id: I9A65C288
legacy_id: P005570
ocr_import_info:
  bdrc_scan_id: W1CZ3883
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T03:30:17'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T19:33:44.320784+00:00'
last_modified: 2022-08-31 03:33:56.724563
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1CZ3883
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1CZ3883
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཚེ་སྒྲུབ་རྡོ་རྗེ་འཕྲེང་བའི་རྒྱུན་ཁྱེར་འཆི་མེད་ཐིག་ལེ།
  author: པདྨ་གླིང་པ།
statistics:
  ocr_word_mean_confidence_index: 0.7498029053394113
  ocr_word_median_confidence_index: 0.8799999952316284
quality: null
bases:
  I1CZ3886:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1CZ3886
      total_pages: 126
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1CZ3886.txt
    statistics:
      ocr_word_median_confidence_index: 0.8799999952316284
      ocr_word_mean_confidence_index: 0.7498029053394113
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
